version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/supersecret123
    ports:
      - "7687:7687"
      - "7474:7474"